baseURL = 'https://mmartinortiz.github.io/website/'
DefaultContentLanguage = "en"
languageCode = 'en-us'
title = "Manuel's bits and bytes"
theme = 'lightbi-hugo'
summaryLength = 30
staticDir = ["static", "assets"]

[Params]
mainSections = ["projects"]
hideAuthor = true
rss = true
selfHosted = true
comments = false
readingTime = false
wordCount = false
useHLJS = true
gcse = false
Lastmod = true
description = "My personal projects, a collection of DIY experiments, software toys and other stuff."

[Author]
name = "Manuel"
website = "https://mmartinortiz.github.io/website"
linkedin = "mmartinortiz"
github = "mmartinortiz"

[[menu.main]]
name = "About"
url = "/about/"
weight = 5
