baseURL = 'https://martin-ortiz.eu'
title = "Manuel's bits and bytes"
theme = 'lightbi-hugo'

# Language & Localization
defaultContentLanguage = "en"
locale = 'en-US'

# Content
summaryLength = 30

# Features
enableRobotsTXT = true
enableGitInfo = false

# Syntax Highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsStyle = "trac"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[pagination]
  pagerSize = 9

[params]
  mainSections = ["projects"]

  # Homepage
  homepageLayout = "blog"

  # Features
  hideAuthor = true
  showPostImage = true
  rss = true
  selfHosted = true
  comments = false
  readingTime = false
  wordCount = false
  useHLJS = true
  gcse = false
  lastmod = true
  socialShare = false
  showRelatedPosts = true

  # Theme-specific
  dateFormat = "02 January 2006"
  previewCardImagePlacement = "bottom"

  description = "My personal projects, a collection of DIY experiments, software toys and other stuff."

[params.author]
  name = "Manuel"
  website = "https://martin-ortiz.eu"
  linkedin = "mmartinortiz"
  github = "mmartinortiz"

[[menu.main]]
name = "About"
url = "/about/"
weight = 5
